version: '3'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - sqlite_data:/app/db.sqlite3
      - static_data:/app/staticfiles
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key-here
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped

volumes:
  sqlite_data:
  static_data: