
services:
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - sqlite_data:/app/data
      - static_data:/app/staticfiles
    env_file:
      - .env.docker
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key-here}
      - DATABASE_DIR=/app/data
    command: >
      bash -c "python manage.py migrate &&
               python create_default_categories.py &&
               python create_default_currencies.py &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 SubCal.wsgi:application"
    restart: unless-stopped

volumes:
  sqlite_data:
  static_data:
