# Generated by Django 5.1.7 on 2025-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($)'), ('GBP', 'GBP (£)'), ('EUR', 'EUR (€)')], default='USD', max_length=3),
        ),
    ]
