# Generated by Django 5.2 on 2025-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_cancellation_date_subscription_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='url',
            field=models.URLField(blank=True, help_text='Website URL for this subscription', null=True),
        ),
    ]
