# Generated by Django 5.2 on 2025-05-02 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0011_assign_subscriptions_to_users'),
    ]

    operations = [
        # First, alter the name field on Category to remove the unique constraint
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),

        # Then, alter the code field on Currency to remove the unique constraint
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3),
        ),

        # Add user field to Category
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # Add user field to Currency
        migrations.AddField(
            model_name='currency',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='currencies',
                to=settings.AUTH_USER_MODEL
            ),
        ),

        # Add unique_together constraint to Category
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),

        # Add unique_together constraint to Currency
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('code', 'user')},
        ),
    ]
