# Generated by Django 5.2 on 2025-05-02 15:31

from django.db import migrations
from django.contrib.auth import get_user_model


def assign_users_to_categories_and_currencies(apps, schema_editor):
    """
    Assign users to existing categories and currencies.
    If no users exist, create an admin user and assign all categories and currencies to them.
    """
    User = get_user_model()
    Category = apps.get_model('subscriptions', 'Category')
    Currency = apps.get_model('subscriptions', 'Currency')

    # Get all categories and currencies without a user
    categories_without_user = Category.objects.filter(user__isnull=True)
    currencies_without_user = Currency.objects.filter(user__isnull=True)

    if categories_without_user.exists() or currencies_without_user.exists():
        # Get the first admin user, or create one if none exists
        admin_user = User.objects.filter(is_superuser=True).first()

        if not admin_user:
            # Create an admin user if none exists
            admin_user = User.objects.create_superuser(
                username='admin',
                email='admin@example.com',
                password='changeme'
            )

        # Assign all categories without a user to the admin user
        categories_without_user.update(user=admin_user)

        # Assign all currencies without a user to the admin user
        currencies_without_user.update(user=admin_user)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_add_user_to_category_and_currency'),
    ]

    operations = [
        migrations.RunPython(assign_users_to_categories_and_currencies),
    ]
